{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wbx",
    "module": "wbx-common",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.62"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.22"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "wbx-common-1.0-plain.jar",
          "url": "wbx-common-1.0-plain.jar",
          "size": 56342,
          "sha512": "32c28264d9f348af94cda68c632581055ce93a80fa575cac169cbc76e0fd69a804afac1cc17a23310d9628657e79f584f698163cb7345bfac6871db6f81ae584",
          "sha256": "22cef1ff7261c18673758b00ba032d2af28343e4a9a3b5d2b36cf0ab551f600f",
          "sha1": "1da63431925747b725ce21ee1153e953a0965dcb",
          "md5": "822a76544b1552445a793cf356e89f35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.62"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.22"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "wbx-common-1.0-plain.jar",
          "url": "wbx-common-1.0-plain.jar",
          "size": 56342,
          "sha512": "32c28264d9f348af94cda68c632581055ce93a80fa575cac169cbc76e0fd69a804afac1cc17a23310d9628657e79f584f698163cb7345bfac6871db6f81ae584",
          "sha256": "22cef1ff7261c18673758b00ba032d2af28343e4a9a3b5d2b36cf0ab551f600f",
          "sha1": "1da63431925747b725ce21ee1153e953a0965dcb",
          "md5": "822a76544b1552445a793cf356e89f35"
        }
      ]
    }
  ]
}
